connexion:
    resource: "@ConnexionBundle/Resources/config/routing.yml"
    prefix:   /

administrateur:
    resource: "@AdministrateurBundle/Resources/config/routing.yml"
    prefix:   /

utilisateur:
    resource: "@UtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /